### ISSUE TITLE
add cmd 

### ISSUE THREAD

**Issue by matt8fr** [HybridDog/superpick#1]
can you add cmd like [this](https://www.youtube.com/watch?v=Y97oSbnNEcI) ?

**Comment by HybridDog** [comment]
l didn't know there was a mc mod called super pickaxe…
l don't add such a command because there are other mods for e.g. replacing nodes in range, changing the tool behaviour with a chatcommand is in my opinion much more inconvenient instead of simply using a second tool.
https://github.com/hybriddog/replacer
https://github.com/HybridDog/command_tool
